apiVersion: v1
kind: deployment

spec:
  containers:
  - name: drone
    image: drone/drone:1.1.0
    env:
    - name: DRONE_KUBERNETES_ENABLED
      value: true
    - name: DRONE_KUBERNETES_NAMESPACE
      value: default
    - name: DRONE_GITHUB_SERVER
      value: https://github.com
    - name: DRONE_SERVER_HOST
      value: https://drone.example.com
    - name: DRONE_SERVER_PROTO
      value: https
    - name: DRONE_GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: drone-secrets
          key: drone_github_client_id
    - name: DRONE_GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: drone-secrets
          key: drone_github_client_secret
    - name: DRONE_RPC_SECRET
      valueFrom:
        secretKeyRef:
          name: drone-secrets
          key: drone_rpc_secret
    ports:
      - containerPort: 80
      - containerPort: 443
