apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-ci-app
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-ci-app
    spec:
      containers:
      - name: drone
        image: drone/drone:1.1.0
        env:
        - name: DRONE_KUBERNETES_ENABLED
          value: "true"
        - name: DRONE_KUBERNETES_NAMESPACE
          value: default
        - name: DRONE_GITHUB_SERVER
          value: https://github.com
        - name: DRONE_SERVER_HOST
          value: https://drone.example.com
        - name: DRONE_SERVER_PROTO
          value: http
        - name: DRONE_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: drone_github_client_id
        - name: DRONE_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: drone_github_client_secret
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: drone_rpc_secret
        resources:
          limits:
            cpu: "1.0"
            memory: 1028Mi
          requests:
            cpu: "0.5"
            memory: 512Mi
        ports:
          - containerPort: 80
          - containerPort: 443
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
