apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
type: Opaque
data:
  drone_github_client_id: "add your secret here"
  drone_github_client_secret: "add your secret here"
  drone_rpc_secret: "add your secret here"
